# -*- coding: utf-8 -*-
"""BaPy_tutorial1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hnSiBeT9eXlL_Jzx_p2M6tTqerWJdCr

# Basic Programming in Python

## Summer Semester, 2023

### Tutorial - 25.04.2023

#### Printing to the Console

 1. Let's keep pace with the tradition and print a message to the console, such as "I love Python!". If you wish, you can print it in any language you want! Don't forget this is your very first program, so be proud! 😎
"""

print()

"""2. Write a program that prints out the lyrics to the song "99 Bottles of Beer" with using one print statement. The first line should be "99 bottles of beer on the wall, 99 bottles of beer..." and the last line should be "No more bottles of beer on the wall, no more bottles of beer. Go to the store and buy some more, 99 bottles of beer on the wall."
"""

print("99 bottles of beer on the wall, 99 bottles of beer ...\nNo more bottles of beer on the wall, no more bottles of beer. Go to the store and buy some more, 99 bottles of beer on the wall.")

"""#### Math Operator Precedence Rules

PEMDAS - LR (LEFT TO RIGHT)


() 

**

*/

+-

3. Think about what the results would be for the following expressions, and then type them to verify your answers!

- 25 / 4 * 4 

- 3 + 4 ** 2

- 4 / 12 + 4

- 3 ** 2

- (5 – 2) * 3

- 16**1/2
"""

25 / 4 * 4

#Try to calculate 25 / (4*4) as well. Why is the result different?
#Play around with math operators and try to solve the rest! :)

"""4. Write a Python program that makes this computation on an integer number (n): n*nn+nnn"""

n = 5

#Type conversion
nn = int(str(n) + str(n))
nnn = int(str(n) + str(n) + str(n))

print(n * nn + nnn)

"""5. Create a program that calculates the area of a rectangle with a width of 4 and a height of 5, and then prints the result with an appropriate massage to the console."""



"""6. Wind often makes the air feel even colder than it is. The Wind Chill Factor (WCF) measures how cold it feels with a given air temperature (T, in degrees Fahrenheit) and wind speed (V, in miles per hour). One formula for the WCF is:

    WCF=35.7+0.6T–35.7(V0.16)+0.43T(V0.16)

Create variables for the temperature T and wind speed V, and then using this formula calculate the WCF.

"""

#The formula to convert from Celcius to Fahrenheit: (Celcius * 9 / 5) + 32

T = 18
V = 10

WCF = 35.7 + 0.6 * (T) - 35.7 * (V * 0.16) + 0.43 * (T) * (V * 0.16)

print(WCF)

"""#### If Statement

7. Create a program that defines a variable day with the value "Tuesday". If the day is a weekday (Monday to Friday), print "It's a weekday". If the day is a weekend day (Saturday or Sunday), print "It's the weekend".
"""

day = "Tuesday"

if day == "Monday" or day == "Tuesday" or day == "Wednesday" or day == "Thursday" or day == "Friday":
  print("It is a weekday!")
else:
  print("It is the weekend!")

"""8. Write a program that generates a random number between 1 and 100 and then prints a message to the console indicating whether that number is divisible by 3, 5, both, or neither."""

import random

#Since randrange(a, b) function is exclusive at the stop value, we added +1.
my_random_number = random.randrange(1, 101)

#It is a good practice to have print statements to check the values of your variables.
print(my_random_number) 

#Remember to use double equal signs "==" to compare different values.
if my_random_number % 3 == 0 and my_random_number % 5 == 0: 
  print("It is divisible by both 3 and 5.")
elif my_random_number % 3 == 0:
  print("It is only divisible by 3.")
elif my_random_number % 5 == 0:
  print("It is only divisible by 5.")
else:
  print("It is neither divisible by 3 nor 5.")